# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://onsonr.dev"
  version "0.6.1"

  depends_on "ipfs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_darwin_x86_64.tar.gz"
      sha256 "ccc117cdf76d726319f702ae4433a40888d84b333f40dc36b071343436a0cefe"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_darwin_arm64.tar.gz"
      sha256 "82e3e12ab25ea9339ae6a66712915d82e889073ac2854d7d41163be47ee89f21"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_linux_x86_64.tar.gz"
        sha256 "603ea252da304ce8f666526c196019d9b7b66d7ec0703a692ea99d06b80a48ac"

        def install
          bin.install "hway"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_linux_arm64.tar.gz"
        sha256 "af38949a385bf886a928ad866a207ae12cdc6c577a97e81d5f35bf9180de80a6"

        def install
          bin.install "hway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local hway node and access it with the hway proxy
    EOS
  end
end
