# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://onsonr.dev"
  version "0.8.3"

  depends_on "ipfs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onsonr/sonr/releases/download/v0.8.3/hway_darwin_x86_64.tar.gz"
      sha256 "33bfe49c99d80bd03c195f475f278034b077b9157e50d727a34e4f1ad97b5b24"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onsonr/sonr/releases/download/v0.8.3/hway_darwin_arm64.tar.gz"
      sha256 "856cc798b966f5f6ca25fccd8701cafec46c869833243e732e2f45227445e6ad"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.8.3/hway_linux_x86_64.tar.gz"
        sha256 "007c4ab15de950054de736c5e635e5f8b2b10503b7e424819af722e3d3634b65"

        def install
          bin.install "hway"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.8.3/hway_linux_arm64.tar.gz"
        sha256 "4ee9fe96f92bab1f05a04e4ada5e90e53b232927059d1a01aa9a4692432c7ee6"

        def install
          bin.install "hway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local hway node and access it with the hway proxy
    EOS
  end
end
