# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hway < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://onsonr.dev"
  version "0.6.1"

  depends_on "ipfs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_0.6.1_Darwin_x86_64.tar.gz"
      sha256 "66915e00e9d0b7c7d7746e7b33dcd1fb405a2d9f3896533883a0cd2322b8867d"

      def install
        bin.install "hway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_0.6.1_Darwin_arm64.tar.gz"
      sha256 "f0efc2b37f049749d61d00a5ff0b7d96c2c2840c214541d68045095cd42d3fdf"

      def install
        bin.install "hway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_0.6.1_Linux_x86_64.tar.gz"
        sha256 "6f06c44b5a42124365cebfd4addc6fbf5b362315155026cbe24a47ad4b0eef0b"

        def install
          bin.install "hway"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.6.1/hway_0.6.1_Linux_arm64.tar.gz"
        sha256 "ace25c6b6a20a050fdacb3f592ed7a90134c8109fbd51d953f1c36b7f838ead7"

        def install
          bin.install "hway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local hway node and access it with the hway proxy
    EOS
  end
end
