# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motr < Formula
  desc "Motr is a proxy for interacting with the Sonr network."
  homepage "https://sonr.io/"
  version "0.4.2"

  depends_on "ipfs"

  on_macos do
    on_intel do
      url "https://github.com/onsonr/sonr/releases/download/v0.4.2/motr_0.4.2_darwin_amd64.tar.gz"
      sha256 "b2c78e46567493862642b7a16c5337dbae38b79345f06250edebb7f1166d5179"

      def install
        bin.install "motr"
      end
    end
    on_arm do
      url "https://github.com/onsonr/sonr/releases/download/v0.4.2/motr_0.4.2_darwin_arm64.tar.gz"
      sha256 "b92b8014407c93992629e2ccfe8efd44d1875699d95a897ee5f154abba4c06e2"

      def install
        bin.install "motr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.4.2/motr_0.4.2_linux_amd64.tar.gz"
        sha256 "4d3a2a6cca1e40673727a80a85e08854373de86e6e9d1347b820d0b5cfe9d9ba"

        def install
          bin.install "motr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.4.2/motr_0.4.2_linux_arm64.tar.gz"
        sha256 "4f7653a09870108fca0aab7f9a74f311349813d2c28c9309b4bd202315b43fc3"

        def install
          bin.install "motr"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Use motr to interact with the Sonr network
    EOS
  end
end
