# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snrd < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://sonr.io"
  version "0.6.4"

  depends_on "ipfs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/snrd/releases/download/v0.6.4/sonr_darwin_x86_64.tar.gz"
      sha256 "f1db4eb40a100a2d252cd2c082782bed0f4b63c1061986710b747364642bafa7"

      def install
        bin.install "snrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/snrd/releases/download/v0.6.4/sonr_darwin_arm64.tar.gz"
      sha256 "869e3ee9b7a46a00fc2602e5006712e17817402e832c9294d1ca710a314a991f"

      def install
        bin.install "snrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sonr-io/snrd/releases/download/v0.6.4/sonr_linux_x86_64.tar.gz"
        sha256 "58f2080c06aaa64a49dfa4e871c45c133e7b70290c78cc3ec023f2ad2697df13"

        def install
          bin.install "snrd"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sonr-io/snrd/releases/download/v0.6.4/sonr_linux_arm64.tar.gz"
        sha256 "de8da37b9b592e7a5e79d57c07a56b587d46960bcac022624ef11df09ece776a"

        def install
          bin.install "snrd"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local sonr node and access it with the hway proxy
    EOS
  end
end
