# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonr < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://onsonr.dev"
  version "0.5.25"

  depends_on "ipfs"

  on_macos do
    on_intel do
      url "https://github.com/onsonr/sonr/releases/download/v0.5.25/sonr_0.5.25_Darwin_x86_64.tar.gz"
      sha256 "31c0c583f2ef020404d21b1a04ddfe8c648ffa73aa5ae8cef88fc57fdac321e4"

      def install
        bin.install "sonrd"
      end
    end
    on_arm do
      url "https://github.com/onsonr/sonr/releases/download/v0.5.25/sonr_0.5.25_Darwin_arm64.tar.gz"
      sha256 "3ddca90a5e094bd8a49eb19e1cfd64ed285bfd1bf7f52bec9818ebc74eb1babd"

      def install
        bin.install "sonrd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.5.25/sonr_0.5.25_Linux_x86_64.tar.gz"
        sha256 "5512fad2def69f54b2969b5e593c8e8d71a2598ba483b2e4408050c82482e575"

        def install
          bin.install "sonrd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.5.25/sonr_0.5.25_Linux_arm64.tar.gz"
        sha256 "4fafcceaf465f2d61930cb32b6c078650132cac7099a338828bbee2d11768184"

        def install
          bin.install "sonrd"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local sonr node and access it with the hway proxy
    EOS
  end
end
