# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonr < Formula
  desc "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
  homepage "https://sonr.io/"
  version "0.5.4"

  depends_on "ipfs"

  on_macos do
    on_intel do
      url "https://github.com/onsonr/sonr/releases/download/v0.5.4/sonr_0.5.4_darwin_amd64.tar.gz"
      sha256 "b2f4b9d29c345d349e7f1847a250d20180b0413c9a9db0c2b61c33a0bf83a0e6"

      def install
        bin.install "sonrd"
      end
    end
    on_arm do
      url "https://github.com/onsonr/sonr/releases/download/v0.5.4/sonr_0.5.4_darwin_arm64.tar.gz"
      sha256 "db9068a7e5f0bd3258098a13e1f09d40cb371895670b87f4dc254f9521a5e410"

      def install
        bin.install "sonrd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.5.4/sonr_0.5.4_linux_amd64.tar.gz"
        sha256 "ffc311413b95cfd27e0d57e4871de330f62e3978da534fe365e748585508f7bb"

        def install
          bin.install "sonrd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onsonr/sonr/releases/download/v0.5.4/sonr_0.5.4_linux_arm64.tar.gz"
        sha256 "e3565f0e6fb9ff57fcda8d0860fe80498f220cbc59af800f3de2450250a45344"

        def install
          bin.install "sonrd"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run a local sonr node and access it with the hway proxy
    EOS
  end
end
